package Supplier;


import static Supplier.Report.Ireport.MyReport;
import static Supplier.database.DB.getConnection;

import static Supplier.SupplierValidation.*;
import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import java.util.HashMap;
import javax.swing.BorderFactory;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Krishan
 */
public class OrderSupplier extends javax.swing.JFrame {

    /**
     *
     * Creates new form Supplier
     */
    Connection connection=null;
    public OrderSupplier() throws SQLException {
         connection=getConnection();
        initComponents();
    }
     public static String Esupid ;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jPanel5 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnView = new javax.swing.JToggleButton();
        btnCancel = new javax.swing.JButton();
        btnOrder = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtSupQty = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        btnUpdateOrder = new javax.swing.JButton();
        btnDeleteOrder = new javax.swing.JButton();
        btnADD = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        cbxSupID = new javax.swing.JComboBox<>();
        cbxItemCode = new javax.swing.JComboBox<>();
        jDateChooser = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Search-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSearch, javax.swing.GroupLayout.DEFAULT_SIZE, 433, Short.MAX_VALUE)
                    .addComponent(jSeparator5))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(0, 18, 50));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(0, 100, 150));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Back-50.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 576, 60, 61));

        jPanel6.setBackground(new java.awt.Color(32, 47, 90));

        jPanel2.setBackground(new java.awt.Color(106, 116, 145));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jButton4.setBackground(new java.awt.Color(204, 180, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Report Card-50.png"))); // NOI18N
        jButton4.setText("Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        btnReset.setBackground(new java.awt.Color(204, 180, 255));
        btnReset.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Clear Symbol-50.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnView.setBackground(new java.awt.Color(204, 180, 255));
        btnView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Compare-50.png"))); // NOI18N
        btnView.setText("View Orders");
        btnView.setToolTipText("");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 180, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Cancel-50.png"))); // NOI18N
        btnCancel.setText("Cancel all");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        btnOrder.setBackground(new java.awt.Color(255, 51, 51));
        btnOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnOrder.setForeground(new java.awt.Color(51, 51, 255));
        btnOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Home-50.png"))); // NOI18N
        btnOrder.setText("Order");
        btnOrder.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(108, 108, 108)
                        .addComponent(btnView)
                        .addGap(102, 102, 102)
                        .addComponent(jButton4))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnOrder)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnCancel))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnView, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(106, 116, 145));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Quantity        :");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item Code     :");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Supplier ID     :");

        txtSupQty.setBackground(new java.awt.Color(106, 116, 145));
        txtSupQty.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtSupQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSupQtyKeyTyped(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(106, 116, 145));

        btnUpdateOrder.setBackground(new java.awt.Color(204, 180, 255));
        btnUpdateOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnUpdateOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Update-50.png"))); // NOI18N
        btnUpdateOrder.setText("Update");
        btnUpdateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateOrderActionPerformed(evt);
            }
        });

        btnDeleteOrder.setBackground(new java.awt.Color(204, 180, 255));
        btnDeleteOrder.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDeleteOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Delete-50_1.png"))); // NOI18N
        btnDeleteOrder.setText("Delete");
        btnDeleteOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteOrderActionPerformed(evt);
            }
        });

        btnADD.setBackground(new java.awt.Color(204, 180, 255));
        btnADD.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnADD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Add-50.png"))); // NOI18N
        btnADD.setText("ADD");
        btnADD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnADDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUpdateOrder)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDeleteOrder)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(46, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUpdateOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnADD, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Order ID         :");

        lblID.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblID.setForeground(new java.awt.Color(255, 255, 255));
        lblID.setText("ID ");

        cbxSupID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose SupplierID" }));
        cbxSupID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSupIDItemStateChanged(evt);
            }
        });
        cbxSupID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxSupIDActionPerformed(evt);
            }
        });

        cbxItemCode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose ItemCode" }));
        cbxItemCode.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxItemCodeItemStateChanged(evt);
            }
        });
        cbxItemCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxItemCodeActionPerformed(evt);
            }
        });

        jDateChooser.setMinSelectableDate(new Date());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Before            :");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSupQty)
                    .addComponent(jSeparator1)
                    .addComponent(jSeparator2)
                    .addComponent(jSeparator3)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .addComponent(lblID)
                    .addComponent(cbxSupID, 0, 153, Short.MAX_VALUE)
                    .addComponent(cbxItemCode, 0, 153, Short.MAX_VALUE)
                    .addComponent(jDateChooser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(44, 44, 44))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(lblID))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(cbxSupID, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbxItemCode, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSupQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jDateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 437, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
int checkOrderAvailable = FindSupplierOrderItemDatabase() ;
        if( checkOrderAvailable >0 )
        {
        
        int Req=JOptionPane.showConfirmDialog(null, "Are You Sure ? ");
        if( SupplierIDvalidation(Esupid) && Req==0)
        {
        CancelallOrderSupplierDatabase() ;
        btnView.setSelected(true);
        Show_Order_SupplierDatabase();
        }
        }
        else
        {
            
            JOptionPane.showMessageDialog(null,"No Orders to Supplier ","Check",JOptionPane.ERROR_MESSAGE);
            
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        SearchJtable();
    }//GEN-LAST:event_txtSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        SupplierMain sm=new SupplierMain();
        sm.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        cbxSupID.setSelectedIndex(0);
        cbxItemCode.setSelectedIndex(0);
        txtSearch.setText(null);
        txtSupQty.setText(null);
        jDateChooser.setDate(null);
        lblID.setText("ID");
        btnView.setSelected(false);
        Show_SETItem_SupplierDatabase();
         cbxItemCode.setEnabled(false);
       btnADD.setEnabled(true);

         
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderActionPerformed
        
       int checkOrderAvailable = FindSupplierOrderItemDatabase() ;
        if( checkOrderAvailable >0 )
        {
        
        try {
            OrderEmailSupplierItem emailobj=new OrderEmailSupplierItem();
            emailobj.setVisible(true);
            dispose();
                    }
        catch (SQLException ex) {
            Logger.getLogger(OrderSupplier.class.getName()).log(Level.SEVERE, null, ex);
                             }
        }
        else
        {
            
            JOptionPane.showMessageDialog(null,"No Order Supplier ","Check",JOptionPane.ERROR_MESSAGE);
            
        }
       
    }//GEN-LAST:event_btnOrderActionPerformed

    private void btnADDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnADDActionPerformed
        
        if(Quantityvalidation(txtSupQty.getText()) && SupplierIDvalidation((String) cbxSupID.getSelectedItem()) && itemCodevalidation((String) cbxItemCode.getSelectedItem()) && jDateChooser.getDate()!=null)
        {
        InsertOrderSupplierDatabase();
        btnView.setSelected(true);
        Show_Order_SupplierDatabase();
        }
         if(jDateChooser.getDate()==null)
    {
          JOptionPane.showMessageDialog(null,"Please Choose Date !");

    }
        
    }//GEN-LAST:event_btnADDActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        //Show_SETItem_SupplierDatabase();
    }//GEN-LAST:event_formWindowActivated

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
       int r=jTable1.getSelectedRow();
     
       
        
        if(btnView.isSelected())
        {
      lblID.setText(jTable1.getValueAt(r, 0).toString());
        cbxSupID.setSelectedItem(jTable1.getValueAt(r, 1).toString());
        cbxItemCode.setSelectedItem(jTable1.getValueAt(r, 2).toString());
        txtSupQty.setText(jTable1.getValueAt(r, 5).toString());
        jDateChooser.setDate((Date) jTable1.getValueAt(r, 6));
       btnADD.setEnabled(false);
        }
        else
        {
         lblID.setText("ID");
        cbxSupID.setSelectedItem(jTable1.getValueAt(r, 1).toString());
        cbxItemCode.setSelectedItem(jTable1.getValueAt(r, 0).toString());
        btnADD.setEnabled(true);
        }
         

        
    }//GEN-LAST:event_jTable1MouseClicked

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
       Esupid= (String) cbxSupID.getSelectedItem();
    }//GEN-LAST:event_formMouseMoved

    private void btnUpdateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateOrderActionPerformed
    if(Quantityvalidation(txtSupQty.getText())&& jDateChooser.getDate()!=null)
        {
       UpadteOrderSupplierDatabase() ;
       btnView.setSelected(true);
        Show_Order_SupplierDatabase();
        } 
    if(jDateChooser.getDate()==null)
    {
          JOptionPane.showMessageDialog(null,"Please Choose Date !");

    }
    }//GEN-LAST:event_btnUpdateOrderActionPerformed

    private void btnDeleteOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteOrderActionPerformed
    if(!"ID".equals(lblID.getText()))
       { DeleteOrderSupplierDatabase() ;
        btnView.setSelected(true);
        Show_Order_SupplierDatabase();
        }
        
    }//GEN-LAST:event_btnDeleteOrderActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        if(btnView.isSelected())
        {
            Show_Order_SupplierDatabase();
        }
        else
        {
                 Show_SETItem_SupplierDatabase();

        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        HashMap param= new HashMap();
        
        String report="C:\\CompanyMSys\\Settings\\Supplier\\PayReport.jasper" ;           
          
          String invoiceIDReport =JOptionPane.showInputDialog(null, "Input Invoice ID");
          if(invoiceIDReport !=null)
          {
          param.put("INVOICEID",invoiceIDReport );
         
         
        try {
            MyReport(report,param);
        } catch (SQLException | JRException ex) {
            Logger.getLogger(SupplierMain.class.getName()).log(Level.SEVERE, null, ex);
        }
        
          }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        Show_SETItem_SupplierDatabase();
       // itemComboLoad() ;
        SupplierComboLoad() ;
         cbxItemCode.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void cbxSupIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSupIDItemStateChanged
       if(cbxSupID.getSelectedIndex()==0)
      {
       cbxItemCode.setEnabled(false);
      }
       else{
       cbxItemCode.setEnabled(true);
       String tmp = cbxItemCode.getItemAt(0);
      cbxItemCode.removeAllItems();
      cbxItemCode.addItem(tmp);
      itemComboLoad(cbxSupID.getSelectedItem().toString());
       }
      
    }//GEN-LAST:event_cbxSupIDItemStateChanged

    private void cbxSupIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxSupIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxSupIDActionPerformed

    private void cbxItemCodeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxItemCodeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxItemCodeItemStateChanged

    private void cbxItemCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxItemCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxItemCodeActionPerformed

    private void txtSupQtyKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSupQtyKeyTyped
       
        char c=evt.getKeyChar() ;
        String x = Character.toString(c);
        if(!((c==KeyEvent.VK_BACKSPACE)  || (c==KeyEvent.VK_DELETE)))
         {  
             if( !Quantityvalidation(x)   )
             {
                getToolkit().beep();
                 evt.consume();
                 
              }
             
         }
        
        
    }//GEN-LAST:event_txtSupQtyKeyTyped

    
    
    
    
    
    
    
    
    public  int FindSupplierOrderItemDatabase() {
      
            
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT COUNT(*) " + "FROM ordersupplieritem WHERE (OrderInvoiceID IS NULL) " ;

            try (PreparedStatement prep = connection.prepareStatement(selectSql)) {

              
             ResultSet rs=prep.executeQuery() ;
              while(rs.next())
               { 
                   return rs.getInt(1) ;
                   
               }
              
            }
        
        catch (Exception e) {
               JOptionPane.showMessageDialog(null,e);

        }
            return 0 ;
    }
    
    
    
    
    
    public void SupplierComboLoad(){
        
            String selectSql = "SELECT * " + "FROM supplier "  ;

            try(Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(selectSql)){
                
               
                String item;
              
               while(rs.next())
               { 
                 
                item=rs.getString(1);
                cbxSupID.addItem(item);
               
               }
           }    
           catch(Exception e)
           {
           }
 }
    
    
      
    public void itemComboLoad(String sid){
        
            String selectSql = "SELECT * FROM `setsupplieritem` WHERE SupplierID="+sid  ;

            try(Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(selectSql)){
                
               
                String item;
              
               while(rs.next())
               { 
                 
                item=rs.getString(1);
                cbxItemCode.addItem(item);
               
               }
           }    
           catch(Exception e)
           {
           }
 }
    
    
    
    
    
    public  void SearchJtable() {
      
           
            String selectSql;
           
            // Create and execute a SELECT SQL statement.
            
            selectSql ="SELECT s.`ItemCode`,s.`SupplierID`, i.`Item_name`, s.`Type`,s. `ETIunit_price` " +"FROM `item_inventory` i , `setsupplieritem` s " + "WHERE i.`Item_code`=  s.`ItemCode` AND (s.SupplierID LIKE '%"+txtSearch.getText()+"%' OR s.ItemCode LIKE '%"+txtSearch.getText()+"%'" +" OR  i.Item_name LIKE '%"+txtSearch.getText()+"%' )"  ;
            
            
            
            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {
                
                

              
              jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
              
         
                
                
            } catch (SQLException ex) {
            Logger.getLogger(Supplier.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    
    
     public  void DeleteOrderSupplierDatabase() {
            
         
            // Prepared statement to insert data
                String insertSql = " DELETE FROM ordersupplieritem WHERE ID = ? AND  OrderInvoiceID IS NULL  " ;

               
                try (PreparedStatement prep = connection.prepareStatement(insertSql)) {
                            String iD_del =lblID.getText();
                        prep.setInt(1,Integer.parseInt(iD_del) );
                         
                    
                       
                       
                      

                        int i=prep.executeUpdate();
                         if(i>0)
                         {
                        JOptionPane.showMessageDialog(null,"Delete Complete" + iD_del);
                         }
                         else
                         {
                             JOptionPane.showMessageDialog(null,"  COMPLETED Orders can not Delete", "Error", JOptionPane.ERROR_MESSAGE);
                         }
        }
        catch (Exception e) {
              JOptionPane.showMessageDialog(null,e);

           
        }
    
      }
    
    
    
    
    
    
     public  void CancelallOrderSupplierDatabase() {
            
         
            // Prepared statement to insert data
                String insertSql = " DELETE FROM ordersupplieritem WHERE SupplierID = ? AND OrderInvoiceID IS NULL  " ;

               
                try (PreparedStatement prep = connection.prepareStatement(insertSql)) {
                        prep.setString(1, Esupid);
                    
                       
                       
                      

                         prep.executeUpdate();
                        JOptionPane.showMessageDialog(null,"Cancel Complete");
        }
        catch (Exception e) {
              JOptionPane.showMessageDialog(null,e);

           
        }
    
      }
    
     
     
      public  void InsertOrderSupplierDatabase() {
            
          java.util.Date date;
               java.sql.Date sqldate;
               
               date= jDateChooser.getDate();
               sqldate=new java.sql.Date(date.getTime());
         
            // Prepared statement to insert data
                String insertSql = " INSERT INTO ordersupplieritem ( SupplierID , ItemCode , Qty , beforeDays ) VALUES ( ? , ? , ? , ? ) " ;

               
                try (PreparedStatement prep = connection.prepareStatement(insertSql)) {
                        prep.setString(1, (String) cbxSupID.getSelectedItem());
                    
                        prep.setString(2, (String) cbxItemCode.getSelectedItem());
                         prep.setString(3, txtSupQty.getText());
                         prep.setDate(4, sqldate);
                       
                      

                        int i=prep.executeUpdate();
                         if(i>0)
                         {
                        JOptionPane.showMessageDialog(null,"Insert Complete");
                         }
                         else
                         {
                             JOptionPane.showMessageDialog(null,"error");
                         }
        }
        catch (Exception e) {
              JOptionPane.showMessageDialog(null,e);

           
        }
    
      }
    
    
      public  void UpadteOrderSupplierDatabase() {
            
         
              java.util.Date date;
               java.sql.Date sqldate;
               
               date= jDateChooser.getDate();
               sqldate=new java.sql.Date(date.getTime());
          
            // Prepared statement to insert data
                String insertSql = " UPDATE ordersupplieritem  SET  Qty = ? , beforeDays = ? WHERE ID = ? AND  OrderInvoiceID IS NULL" ;

               
                try (PreparedStatement prep = connection.prepareStatement(insertSql)) {
                        prep.setString(3,lblID.getText());
                         prep.setString(1,txtSupQty.getText() );
                         prep.setDate(2,sqldate );

                      

                        int i=prep.executeUpdate();
                         if(i>0)
                         {
                        JOptionPane.showMessageDialog(null,"Upadate Complete");
                         }
                         else
                         {
                             JOptionPane.showMessageDialog(null,"error");
                         }
        }
        catch (Exception e) {
              JOptionPane.showMessageDialog(null,e);

           
        }
    
      }
    
    
    
      public  void Show_SETItem_SupplierDatabase() {
      
            
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT s.`ItemCode`,s.`SupplierID`, i.`Item_name`, s.`Type`,s. `ETIunit_price` " +"FROM `item_inventory` i , `setsupplieritem` s" +
" WHERE  i.`Item_code`=  s.`ItemCode` ";

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {

              
      
                jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
              
            }
        
        catch (Exception e) {
               JOptionPane.showMessageDialog(null,"Error");

        }
    
    }
      
      
      /*
      
       public  double Total_Order_SupplierDatabase() throws SQLException {
      
            
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT ETIunit_price " + "FROM setsupplieritem WHERE ItemCode = ? AND SupplierID = ? ";

            try(PreparedStatement prep2= connection.prepareStatement(selectSql);)  {
                        prep2.setString(1, (String) cbxItemCode.getSelectedItem());
                    
                       prep2.setString(2, (String) cbxSupID.getSelectedItem());
                        
                      

                         
                         
                         
                 ResultSet  resultSet=prep2.executeQuery();
               while(resultSet.next())
               {
                   return resultSet.getDouble(1) ;
               }
       }
            return 0;
       }*/
      
       public  void Show_Order_SupplierDatabase()  {
      
            
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT * " + "FROM ordersupplieritem ";

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {

              
      
                jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
              
            } catch (SQLException ex) {
            Logger.getLogger(OrderSupplier.class.getName()).log(Level.SEVERE, null, ex);
        }
       }
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Supplier().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(OrderSupplier.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnADD;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDeleteOrder;
    private javax.swing.JButton btnOrder;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnUpdateOrder;
    private javax.swing.JToggleButton btnView;
    private javax.swing.JComboBox<String> cbxItemCode;
    private javax.swing.JComboBox<String> cbxSupID;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JDateChooser jDateChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblID;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSupQty;
    // End of variables declaration//GEN-END:variables
}
