package Supplier;


import static Supplier.OrderSupplier.Esupid;
import static Supplier.SupplierValidation.InternetConnection;
import static Supplier.database.DB.getConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Krishan
 */

public class OrderEmailSupplierItem extends javax.swing.JFrame {

    /**
     * Creates new form OrderEmailSupplierItem
     */
     Connection  connection=null;
    public OrderEmailSupplierItem() throws SQLException {
        connection = getConnection();
        initComponents();
       
    }

 
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnEmail = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        lblEmail2 = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        cbxSupID = new javax.swing.JComboBox<>();
        lblEmail3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(106, 116, 145));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        btnEmail.setBackground(new java.awt.Color(204, 180, 255));
        btnEmail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Settings-48.png"))); // NOI18N
        btnEmail.setText("Email");
        btnEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEmailActionPerformed(evt);
            }
        });

        btnCancel.setBackground(new java.awt.Color(204, 180, 255));
        btnCancel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnCancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Delete-50.png"))); // NOI18N
        btnCancel.setText("Cancel all");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        lblEmail2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail2.setForeground(new java.awt.Color(255, 51, 51));
        lblEmail2.setText("Send To");

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(102, 255, 255));
        lblEmail.setText("Email");

        cbxSupID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxSupIDItemStateChanged(evt);
            }
        });

        lblEmail3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblEmail3.setForeground(new java.awt.Color(255, 51, 51));
        lblEmail3.setText("SupplierID");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lblEmail2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(199, 199, 199)
                        .addComponent(btnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(173, 173, 173)
                        .addComponent(btnCancel)
                        .addGap(18, 18, 18)
                        .addComponent(lblEmail3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbxSupID, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 94, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addGap(35, 35, 35))))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(20, 20, 20)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(788, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 325, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxSupID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEmail3))
                    .addComponent(lblEmail2))
                .addGap(32, 32, 32))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(390, Short.MAX_VALUE)
                    .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(27, 27, 27)))
        );

        jPanel5.setBackground(new java.awt.Color(0, 18, 50));

        btnBack.setBackground(new java.awt.Color(0, 100, 150));
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Back-50.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnBack, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 60, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        dispose();
        OrderSupplier sm;
         try {
             sm = new OrderSupplier();
              sm.setVisible(true);
         } catch (SQLException ex) {
             Logger.getLogger(OrderEmailSupplierItem.class.getName()).log(Level.SEVERE, null, ex);
         }
       
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEmailActionPerformed

        
        int Req=JOptionPane.showConfirmDialog(null, "Are You Sure ? ");
        if( Req==0 && InternetConnection ())
        {
        
        UpdateSupplierDatabase();
        JOptionPane.showMessageDialog(null,"Email sent Successful ! To "+lblEmail.getText(),"Successful",JOptionPane.INFORMATION_MESSAGE);
        
        
        
            
        
        }
        
        
    }//GEN-LAST:event_btnEmailActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
         Esupid=(String) cbxSupID.getSelectedItem();
        try {
             OrderSupplier Oes= new OrderSupplier();
             Oes.CancelallOrderSupplierDatabase();
             
              
              
            
         } catch (SQLException ex) {
             Logger.getLogger(OrderEmailSupplierItem.class.getName()).log(Level.SEVERE, null, ex);
         }
    
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        SupplierComboLoad();
        ShowSupplierOrderItemDatabase();
        getSupplierEmail();
        if(cbxSupID.getSelectedIndex()==-1)
                
                 {

                     btnBack.doClick();
            
                 }
        
       
    }//GEN-LAST:event_formWindowActivated

    private void cbxSupIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxSupIDItemStateChanged
         
        ShowSupplierOrderItemDatabase();
        getSupplierEmail();
        
    }//GEN-LAST:event_cbxSupIDItemStateChanged

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
       
    }//GEN-LAST:event_formWindowStateChanged

    
    
    
    
    
     public  void getSupplierEmail() {
      
            
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT DISTINCT(S_Email) " + "FROM supplier WHERE  SupplierID =?" ;

            try (PreparedStatement prepz = connection.prepareStatement(selectSql))
            {
                prepz.setString(1, (String) cbxSupID.getSelectedItem());
                ResultSet rs=prepz.executeQuery();
                
                while(rs.next())
                {
                    
                    lblEmail.setText(rs.getString(1));
                }
              
            }
        
        catch (Exception e) {
               JOptionPane.showMessageDialog(null,"Error");

        }
    
    }
    
    
    
    
    public  void UpdateSupplierDatabase() {
         
            // Prepared statement to insert data
                String insertSql = " INSERT INTO ordersupplierinvoice(SupplierID) VALUES(?);"  ;
                //String UPDATESql ="UPDATE ordersupplieritem SET OrderInvoiceID =(SELECT LAST_INSERT_ID() FROM ordersupplierinvoice  )  WHERE SupplierID = ?  AND OrderInvoiceID IS NULL " ;
               String Sql= " SELECT MAX(InvoiceID) FROM ordersupplierinvoice WHERE SupplierID = ?";
                try (PreparedStatement prep = connection.prepareStatement(insertSql) ;
                        PreparedStatement prep2= connection.prepareStatement(Sql);)  {
                        prep.setString(1, (String) cbxSupID.getSelectedItem());
                    
                       prep2.setString(1,(String) cbxSupID.getSelectedItem());
                        
                      

                         prep.executeUpdate();
                         
                         
                 ResultSet  resultset=prep2.executeQuery();
                    int INVOID = 0;
                   while(resultset.next()){
                    
                                       INVOID= resultset.getInt(1);
                                         
                                        //JOptionPane.showMessageDialog(null,"Insert Complete" + INVOID);
                          }
                         
                        getSupplierOrderItemDatabase(INVOID);
                        
        }
        catch (Exception e) {
              JOptionPane.showMessageDialog(null,e);

           
        }
    
    }
    
    
    
     public  void ShowSupplierOrderItemDatabase() {
      
            
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT * " + "FROM ordersupplieritem WHERE (OrderInvoiceID IS NULL) AND SupplierID = "+ (String) cbxSupID.getSelectedItem() ;

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {

              
      
                jTable1.setModel(DbUtils.resultSetToTableModel(resultSet));
              
            }
        
        catch (Exception e) {
               JOptionPane.showMessageDialog(null,"Error");

        }
    
    }
    
     
     
     
      
     public  void getSupplierOrderItemDatabase(int invo) {
      
            
     
            // Create and execute a SELECT SQL statement.
            String selectSql = "SELECT  i.Item_name , o.Qty , o.OrderDate , o.beforeDays , s.S_Email , m.Type " + "FROM ordersupplieritem o , item_inventory i ,supplier s ,setsupplieritem m WHERE i.Item_code = o.ItemCode  AND m.ItemCode= o.ItemCode AND m.SupplierID = o.SupplierID AND s.SupplierID = o.SupplierID AND OrderInvoiceID = " + invo ;

            try (Statement statement = connection.createStatement();
                 ResultSet resultSet = statement.executeQuery(selectSql)) {

              String EMAIL="<caption><h1><u>L.N.D GRAPHICS</u></h1></caption><h2 style=\"background-color:red;\">INVOICE ID : " +invo+"</h2><table border=5 width=100% height=100% > <tr><th>Item Name</th><th>Type</th><th>Quantity</th><th>Order Date</th> <th>Before Date</th></tr>" ;
              String  EMAILadd =null ;
                while(resultSet.next()){
                    
                                       EMAIL +="<tr> <td>" + resultSet.getString(1) + "</td> <td>"+resultSet.getString(6)+ "</td> <td>"+resultSet.getString(2) +"</td> <td>" +resultSet.getString(3)+  "</td> <td>" +resultSet.getString(4)+ "</td> </tr> ";
                                         EMAILadd=resultSet.getString(5) ;
                                          }
                                           EMAIL +="</table>" ;
                                          // return EMAIL ;
                                          EmailSupplierInterface ee=new  EmailSupplierInterface();
                                          ee.generateAndSendEmail(EMAIL,EMAILadd);
                                         // JOptionPane.showMessageDialog(null,EMAIL);
            }
        
        catch (Exception e) {
               JOptionPane.showMessageDialog(null,e);

        }
    
    }
     
     
     
     
     
     
     
     
      
    public void SupplierComboLoad(){
           cbxSupID.removeAllItems();
            String selectSql = "SELECT DISTINCT(SupplierID) " + "FROM ordersupplieritem WHERE (OrderInvoiceID IS NULL)"  ;

            try(Statement statement = connection.createStatement();
                 ResultSet rs = statement.executeQuery(selectSql)){
                
               
                String cSupid;
              
               while(rs.next())
               { 
                 
                cSupid=rs.getString(1);
                cbxSupID.addItem(cSupid);
               
               }
           }    
           catch(Exception e)
           {
           }
 }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderEmailSupplierItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderEmailSupplierItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderEmailSupplierItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderEmailSupplierItem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new OrderEmailSupplierItem().setVisible(true);
                    
                } catch (SQLException ex) {
                    Logger.getLogger(OrderEmailSupplierItem.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnEmail;
    private javax.swing.JComboBox<String> cbxSupID;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail2;
    private javax.swing.JLabel lblEmail3;
    // End of variables declaration//GEN-END:variables
}
