/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fleetz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import fleet.DBconnect;
import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.proteanit.sql.DbUtils;
import static fleetz.dValidation.VIDValidation;
import static fleetz.dValidation.DIDValidation;
import static fleetz.dValidation.CIDValidation;
import static fleetz.dValidation.DateValidation;
import static fleetz.dValidation.StatusValidation;
import static fleetz.dValidation.AddressValidation;
import static fleetz.dValidation.NameValidation;
import static fleetz.dValidation.Phonevalidation;
import static fleetz.dValidation.DistanceValidation;
import static fleetz.dValidation.RateValidation;


/**
 *
 * @author Pavilion
 */
public class deliver extends javax.swing.JFrame {
    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form deliver
     */
    public deliver() throws SQLException {
        initComponents();
        conn = DBconnect.connect();
      
        CIDload();
          btnLoadVDelivery.doClick();
    }
    public void CIDload(){
        try{
            String sql="SELECT CID FROM customer";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            String CID="";
            
            while(rs.next()){
                CID=rs.getString("CID");
                txtCID.addItem(CID);
            }
        }
        catch(Exception e){
            
        }
        
    }
public static String custId;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbType = new javax.swing.JComboBox<>();
        btnAvailableSearch = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jdate = new com.toedter.calendar.JDateChooser();
        addID = new javax.swing.JButton();
        btnAddDelivery = new javax.swing.JButton();
        btnLoadVDelivery = new javax.swing.JButton();
        btnUpdateDelivery = new javax.swing.JButton();
        lblVID = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblDID = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        dStatus = new javax.swing.JComboBox<>();
        btnNext = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        txtDistance = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        btnPrint = new javax.swing.JButton();
        txtCID = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel7.setText("Delivery");

        txtSearch.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtSearch.setBorder(null);
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Search-50.png"))); // NOI18N
        btnSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSearchMouseClicked(evt);
            }
        });
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(781, 781, 781)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(32, 47, 90));

        jPanel4.setBackground(new java.awt.Color(106, 116, 145));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vehicle ID              :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Vehicle Type         :");

        cmbType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Car", "Van", "Pickup", "Minitruck", "Truck" }));
        cmbType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbTypeItemStateChanged(evt);
            }
        });

        btnAvailableSearch.setText("Search");
        btnAvailableSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAvailableSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Customer ID         :");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Shipping Address :");

        txtAddress.setBackground(new java.awt.Color(106, 116, 145));
        txtAddress.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtAddress.setForeground(new java.awt.Color(255, 255, 255));
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Customer Name   :");

        txtName.setBackground(new java.awt.Color(106, 116, 145));
        txtName.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtName.setForeground(new java.awt.Color(255, 255, 255));
        txtName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Contact                 :");

        txtContact.setBackground(new java.awt.Color(106, 116, 145));
        txtContact.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtContact.setForeground(new java.awt.Color(255, 255, 255));
        txtContact.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Deliver Date           :");

        jdate.setDateFormatString("yyyy-MM-dd");

        addID.setBackground(new java.awt.Color(204, 180, 255));
        addID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        addID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Add-50.png"))); // NOI18N
        addID.setText("Add");
        addID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addIDActionPerformed(evt);
            }
        });

        btnAddDelivery.setBackground(new java.awt.Color(204, 180, 255));
        btnAddDelivery.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnAddDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Save-50.png"))); // NOI18N
        btnAddDelivery.setText("Save Add");
        btnAddDelivery.setBorder(null);
        btnAddDelivery.setBorderPainted(false);
        btnAddDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDeliveryActionPerformed(evt);
            }
        });

        btnLoadVDelivery.setBackground(new java.awt.Color(204, 180, 255));
        btnLoadVDelivery.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnLoadVDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Settings-48.png"))); // NOI18N
        btnLoadVDelivery.setText("Load");
        btnLoadVDelivery.setBorder(null);
        btnLoadVDelivery.setBorderPainted(false);
        btnLoadVDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadVDeliveryActionPerformed(evt);
            }
        });

        btnUpdateDelivery.setBackground(new java.awt.Color(204, 180, 255));
        btnUpdateDelivery.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnUpdateDelivery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Update-50.png"))); // NOI18N
        btnUpdateDelivery.setText("Update");
        btnUpdateDelivery.setBorder(null);
        btnUpdateDelivery.setBorderPainted(false);
        btnUpdateDelivery.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateDeliveryActionPerformed(evt);
            }
        });

        lblVID.setForeground(new java.awt.Color(255, 255, 255));
        lblVID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Delivery ID            :");

        lblDID.setForeground(new java.awt.Color(255, 255, 255));
        lblDID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Status                    :");

        dStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose", "Started", "Complete", "Cancelled" }));

        btnNext.setBackground(new java.awt.Color(204, 180, 255));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnNext.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/next.png"))); // NOI18N
        btnNext.setText("Next");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        txtDistance.setBackground(new java.awt.Color(106, 116, 145));
        txtDistance.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtDistance.setForeground(new java.awt.Color(255, 255, 255));
        txtDistance.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Distance                :");

        txtRate.setBackground(new java.awt.Color(106, 116, 145));
        txtRate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtRate.setForeground(new java.awt.Color(255, 255, 255));
        txtRate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Rate                       :");

        btnPrint.setBackground(new java.awt.Color(204, 180, 255));
        btnPrint.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Report Card-50.png"))); // NOI18N
        btnPrint.setText("Print");
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        txtCID.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choose" }));
        txtCID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(addID, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAddDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdateDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAvailableSearch)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblVID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(118, 118, 118)))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(dStatus, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDID, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnLoadVDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 816, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addContainerGap(3123, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(btnAvailableSearch)
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(lblVID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(lblDID, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtCID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jdate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(dStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtDistance, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addID, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLoadVDelivery, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 1, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPrint, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(btnAddDelivery, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnUpdateDelivery, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(376, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));

        jButton4.setBackground(new java.awt.Color(204, 180, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Back-50.png"))); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        dispose();
        m me=new m();
        me.setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int r=jTable1.getSelectedRow();
        lblVID.setText((String) jTable1.getValueAt(r, 0).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void addIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addIDActionPerformed
        
        if(VIDValidation(lblVID.getText())){
        try{
            String sql="SELECT `AUTO_INCREMENT` FROM  INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = 'itp' AND   TABLE_NAME   = 'deliver';";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            rs.next();
            lblDID.setText(rs.getString(1));
            addID.setEnabled(false);
            btnAvailableSearch.setEnabled(false);
            btnSearch.setEnabled(false);
            btnUpdateDelivery.setEnabled(false);
            btnNext.setEnabled(false);
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "no values");
        }
        }
        
         // TODO add your handling code here:
    }//GEN-LAST:event_addIDActionPerformed

    private void btnAddDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDeliveryActionPerformed
        // TODO add your handling code here:
        
        if(VIDValidation(lblVID.getText()) && DIDValidation(lblDID.getText()) && CIDValidation(txtCID.getSelectedItem().toString()) && DateValidation(((JTextField)jdate.getDateEditor().getUiComponent()).getText()) &&StatusValidation(dStatus.getSelectedItem().toString())) {

        try{

            String sql="INSERT INTO deliver (DID,VID,CID,Date,Status,Address,CName,Contact,Distance,Rate) VALUES (?,?,?,?,?,?,?,?,NULL,NULL)";
            pst=conn.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(lblDID.getText()));
            pst.setInt(2,Integer.parseInt(lblVID.getText()));
            pst.setInt(3,Integer.parseInt(txtCID.getSelectedItem().toString()));
            pst.setString(4,((JTextField)jdate.getDateEditor().getUiComponent()).getText());
            pst.setString(5,dStatus.getSelectedItem().toString());
            pst.setString(6,txtAddress.getText());
            pst.setString(7,txtName.getText());
            pst.setString(8,txtContact.getText());

            int i=pst.executeUpdate();

            if(i>0){

                JOptionPane.showMessageDialog(null,"Submitted");
                if(dStatus.getSelectedItem().toString().equals("Started"))
                {
                    String av="UPDATE vehicle SET Availability='No' where VID=?";
                    pst=conn.prepareStatement(av);
                    pst.setInt(1,Integer.parseInt(lblVID.getText()));
                    int x=pst.executeUpdate();
                    addID.setEnabled(true);
                    btnAvailableSearch.setEnabled(true);
                    btnSearch.setEnabled(true);
                    btnUpdateDelivery.setEnabled(true);
                    btnNext.setEnabled(true);
                
                }
                

            }
            else{
                JOptionPane.showMessageDialog(null,"Wrong input");
            }

        }
        catch(SQLException | NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);

        }
        }
        
    }//GEN-LAST:event_btnAddDeliveryActionPerformed

    private void btnLoadVDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadVDeliveryActionPerformed
        // TODO add your handling code here:
        try{
            String sql="select * from deliver";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
         //   jTable1.setEnabled(false);
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "no values");

        }
        addID.setEnabled(true);
        btnAvailableSearch.setEnabled(true);
        btnSearch.setEnabled(true);
        btnUpdateDelivery.setEnabled(true);
        btnNext.setEnabled(true);
        lblVID.setText(null);
        lblDID.setText(null);
        txtCID.setSelectedIndex(0);
        jdate.setDate(null);
        dStatus.setSelectedIndex(0);
        txtAddress.setText(null);
        txtName.setText(null);
        txtContact.setText(null);
        txtDistance.setText(null);
        txtRate.setText(null);
    }//GEN-LAST:event_btnLoadVDeliveryActionPerformed

    private void btnUpdateDeliveryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateDeliveryActionPerformed
        // TODO add your handling code here:
        if(VIDValidation(lblVID.getText()) && DIDValidation(lblDID.getText()) && CIDValidation(txtCID.getSelectedItem().toString()) && DateValidation(((JTextField)jdate.getDateEditor().getUiComponent()).getText()) &&StatusValidation(dStatus.getSelectedItem().toString()) &&AddressValidation(txtAddress.getText()) &&NameValidation(txtName.getText()) &&Phonevalidation(txtContact.getText())&&DistanceValidation(txtDistance.getText())&&RateValidation(txtRate.getText())){
        try{
            String sql="UPDATE deliver SET CID=? , Date=? , Status=? , Address=? , CName=? , Contact=? , Distance=? , Rate=? WHERE DID=?";
            pst=conn.prepareStatement(sql);
            
            
            pst.setInt(1,Integer.parseInt(txtCID.getSelectedItem().toString()));
            pst.setString(2,((JTextField)jdate.getDateEditor().getUiComponent()).getText());
            pst.setString(3,dStatus.getSelectedItem().toString());
            pst.setString(4,txtAddress.getText());
            pst.setString(5,txtName.getText());
            pst.setString(6,txtContact.getText());
            pst.setDouble(7,Double.parseDouble(txtDistance.getText()));
            pst.setDouble(8,Double.parseDouble(txtRate.getText()));
            pst.setInt(9,Integer.parseInt(lblDID.getText()));
            int i=pst.executeUpdate();

            if(i>0){

                JOptionPane.showMessageDialog(null,"Submitted");
                if(!"Started".equals(dStatus.getSelectedItem().toString()))
                {
                    String av="UPDATE vehicle SET Availability='Yes' where VID=?";
                    pst=conn.prepareStatement(av);
                    pst.setInt(1,Integer.parseInt(lblVID.getText()));
                    int x=pst.executeUpdate();
                
                }
                btnLoadVDelivery.doClick();

            }
            else{
                JOptionPane.showMessageDialog(null,"Wrong input");
            }

        }
        catch(SQLException | NumberFormatException | HeadlessException e){
            JOptionPane.showMessageDialog(null,e);

        }
        }
    }//GEN-LAST:event_btnUpdateDeliveryActionPerformed

    private void btnAvailableSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAvailableSearchActionPerformed
        // TODO add your handling code here:
         try{
            String sql="SELECT * FROM vehicle WHERE Type=? AND Availability='Yes'";
            pst=conn.prepareStatement(sql);
            pst.setString(1,cmbType.getSelectedItem().toString());
            rs=pst.executeQuery();
            jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
         catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnAvailableSearchActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        int r=jTable2.getSelectedRow();
        lblDID.setText((String) jTable2.getValueAt(r, 0).toString());
        lblVID.setText((String) jTable2.getValueAt(r, 1).toString());
        txtCID.setSelectedItem( jTable2.getValueAt(r, 2).toString());
        try {
            Date date;
            date = new SimpleDateFormat("yyyy-MM-dd").parse(jTable2.getValueAt(r, 3).toString());
            jdate.setDate(date);
        } catch (ParseException ex) {
            Logger.getLogger(vehiclePayment.class.getName()).log(Level.SEVERE, null, ex);
        }
        dStatus.setSelectedItem((String) jTable2.getValueAt(r, 4).toString());
        txtAddress.setText((String) jTable2.getValueAt(r, 5).toString());
        txtName.setText((String) jTable2.getValueAt(r, 6).toString());
        txtContact.setText((String) jTable2.getValueAt(r, 7).toString());
        if((jTable2.getValueAt(r, 8) )!=null && (jTable2.getValueAt(r, 9))!=null)
        {
            txtDistance.setText((String) jTable2.getValueAt(r, 8).toString());
            txtRate.setText((String) jTable2.getValueAt(r, 9).toString());
        }
    }//GEN-LAST:event_jTable2MouseClicked

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSearchMouseClicked
        // TODO add your handling code here:
        try{
            String sql="SELECT * FROM deliver WHERE DID=?";
            pst=conn.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(txtSearch.getText()));
            rs=pst.executeQuery();
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            e.printStackTrace();
        }

    }//GEN-LAST:event_btnSearchMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        String did = lblDID.getText();
        if(did.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "Delivery ID is Empty");
        }
        else{
        try {
            custId=(String) txtCID.getSelectedItem() ;
            AddOrder ao=new AddOrder();
            ao.setDID(did);
            ao.setVisible(true);
            //   AddOrder ao=new AddOrder(lblDID.getText());
        } catch (SQLException ex) {
            Logger.getLogger(deliver.class.getName()).log(Level.SEVERE, null, ex);
        }
        }
    }//GEN-LAST:event_btnNextActionPerformed

    
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        String vid = lblVID.getText();
        String did = lblDID.getText();
        String cid = txtCID.getSelectedItem().toString();
        String ddate = ((JTextField)jdate.getDateEditor().getUiComponent()).getText();
        String stat = dStatus.getSelectedItem().toString();
        String add = txtAddress.getText();
        String name = txtName.getText();
        String c = txtContact.getText();
        String d = txtDistance.getText();
        String r = txtRate.getText();
        Delivery bill;
        try {
            bill = new Delivery();
            bill.set(vid,did,cid,ddate,stat,add,name,c,d,r);
        } catch (SQLException ex) {
            Logger.getLogger(deliver.class.getName()).log(Level.SEVERE, null, ex);
        }
        
       // bill.setVisible(true);
        
        
       

    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtCIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCIDActionPerformed
        // TODO add your handling code here:
        if(txtCID.getSelectedIndex()!=0)
        { try{
            String sql="SELECT Cname,CtelNo,Caddress FROM customer WHERE CID=?";
            pst=conn.prepareStatement(sql);
            pst.setInt(1,Integer.parseInt(txtCID.getSelectedItem().toString()));
            rs=pst.executeQuery();
            String nm="",num="",add="";
            while (rs.next()){
                add=rs.getString("Caddress");
                nm=rs.getString("Cname");
                num=rs.getString("CtelNo");
            }
            txtAddress.setText(add);
            txtName.setText(nm);
            txtContact.setText(num);
            
            
        }
        catch(Exception e){
            e.printStackTrace();
        } 
        }
    }//GEN-LAST:event_txtCIDActionPerformed

    private void cmbTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbTypeItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTypeItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(deliver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(deliver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(deliver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(deliver.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new deliver().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(deliver.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addID;
    private javax.swing.JButton btnAddDelivery;
    private javax.swing.JButton btnAvailableSearch;
    private javax.swing.JButton btnLoadVDelivery;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdateDelivery;
    private javax.swing.JComboBox<String> cmbType;
    private javax.swing.JComboBox<String> dStatus;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private com.toedter.calendar.JDateChooser jdate;
    private javax.swing.JLabel lblDID;
    private javax.swing.JLabel lblVID;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JComboBox<String> txtCID;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtDistance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
