package Inventory;



import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.*;
import net.proteanit.sql.DbUtils;
import static Inventory.partvalid.ItemCodevalidation;
import static Inventory.partvalid.Namevalidation;
import static Inventory.partvalid.Quentityvalidation;
import static Inventory.partvalid.Pricevalidation;
import java.awt.Dimension;
//import static newpackage.partvalid.isThisDateValid;
import net.sf.jasperreports.view.*;
import net.sf.jasperreports.engine.*;
import java.util.Date;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hp
 */
public class additems extends javax.swing.JFrame {
       
    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;

    /**
     * Creates new form additems
     */
    public additems() {
         initComponents();
        try {
            conn = connection.condb();
        } catch (SQLException ex) {
            Logger.getLogger(additems.class.getName()).log(Level.SEVERE, null, ex);
        }
        updatetab();
        upt();
    }
    private void updatetab(){
        try{
        String sql="select Item_code,Item_name,Quantity,unitPrice from Item_inventory";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
         jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "table not found");
           
            
        }
    }
          private void upt(){
        try{
        String sql="select * from updt";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
         jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, "table not found");
           
            
        }
          }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        txtcode = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        txtquentity = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddItem_jButton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        txtprice = new javax.swing.JTextField();
        txtdate = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        textsrch = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 18, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(64, 407));

        jButton6.setBackground(new java.awt.Color(0, 100, 150));
        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Back-50.png"))); // NOI18N
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(648, Short.MAX_VALUE)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 710));

        jPanel2.setBackground(new java.awt.Color(32, 47, 90));

        jPanel4.setBackground(new java.awt.Color(106, 116, 145));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(106, 116, 145));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Add Items", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Adobe Caslon Pro", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtcode.setBackground(new java.awt.Color(106, 116, 145));
        txtcode.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtcode.setForeground(new java.awt.Color(255, 255, 255));
        txtcode.setBorder(null);
        txtcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcodeActionPerformed(evt);
            }
        });
        jPanel5.add(txtcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 130, 20));
        jPanel5.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 130, 10));

        txtname.setBackground(new java.awt.Color(106, 116, 145));
        txtname.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtname.setForeground(new java.awt.Color(255, 255, 255));
        txtname.setBorder(null);
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        jPanel5.add(txtname, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 130, 20));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 130, 10));

        txtquentity.setBackground(new java.awt.Color(106, 116, 145));
        txtquentity.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtquentity.setForeground(new java.awt.Color(255, 255, 255));
        txtquentity.setBorder(null);
        txtquentity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtquentityActionPerformed(evt);
            }
        });
        jPanel5.add(txtquentity, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 120, 129, 20));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 129, 10));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Added Date          :");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Quantity               :");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Item Name          :");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Item Code           :");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, -1, -1));

        AddItem_jButton1.setBackground(new java.awt.Color(204, 180, 255));
        AddItem_jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        AddItem_jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Add-50.png"))); // NOI18N
        AddItem_jButton1.setText("Add Items");
        AddItem_jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddItem_jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(AddItem_jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 280, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 180, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Delete-50.png"))); // NOI18N
        jButton1.setText("Delete");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 280, 143, 59));

        jButton2.setBackground(new java.awt.Color(204, 180, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Update-50.png"))); // NOI18N
        jButton2.setText("Update");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 145, 54));

        jButton3.setBackground(new java.awt.Color(204, 180, 255));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Clear Symbol-50.png"))); // NOI18N
        jButton3.setText("Clear");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 143, 54));

        jButton4.setBackground(new java.awt.Color(204, 180, 255));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Report Card-50.png"))); // NOI18N
        jButton4.setText("Generate Report");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 420, 300, 51));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Price(one item)    :");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 130, -1));
        jPanel5.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 130, 10));

        txtprice.setBackground(new java.awt.Color(106, 116, 145));
        txtprice.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtprice.setForeground(new java.awt.Color(255, 255, 255));
        txtprice.setBorder(null);
        jPanel5.add(txtprice, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 210, 130, -1));

        txtdate.setDateFormatString("yyyy-MM-dd");
        jPanel5.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 130, -1));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 330, 500));

        jTable1.setBackground(new java.awt.Color(204, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Item_Code", "Item_Name", "Quentity", "Price"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 443, 170));

        jTable2.setBackground(new java.awt.Color(204, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "code", "quentity", "date"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 280, 440, 240));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Main Inventory");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Updated Items");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 250, -1, -1));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 825, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 538, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 940, 650));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        textsrch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        textsrch.setBorder(null);
        textsrch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textsrchActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8-Search-50.png"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 224, Short.MAX_VALUE)
                    .addComponent(textsrch))
                .addContainerGap(644, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(textsrch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, 940, 80));

        setSize(new java.awt.Dimension(1016, 748));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textsrchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textsrchActionPerformed
        // TODO add your handling code here:
               try{
           String sql="select * from Item_inventory where Item_code=?";
           pst=conn.prepareStatement(sql);
           pst.setString(1,textsrch.getText());
           rs=pst.executeQuery();
           
           if(rs.next()){
               String a10=rs.getString("Item_code");
               txtcode.setText(a10);
               
               String a11=rs.getString("Item_name");
               txtname.setText(a11);
               
               String a12=rs.getString("Quantity");
               txtquentity.setText(a12);
               
               Date a13=rs.getDate("AddDate");
               txtdate.setDate(a13);
               
               String a14=rs.getString("unitPrice");
               txtprice.setText(a14);
               
               
               rs.close();
           }
           else 
                JOptionPane.showMessageDialog(null, "no values");
           
       }
       catch(Exception e){
           JOptionPane.showMessageDialog(null, e);
           
           
           
       }
    }//GEN-LAST:event_textsrchActionPerformed

    private void txtcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcodeActionPerformed

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void txtquentityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtquentityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtquentityActionPerformed

    private void AddItem_jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddItem_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(ItemCodevalidation(txtcode.getText())&&Namevalidation(txtname.getText())&&Quentityvalidation(txtquentity.getText())&&Pricevalidation(txtprice.getText())){
          java.util.Date date;
               java.sql.Date sqldate;
               
               date= txtdate.getDate();
               sqldate=new java.sql.Date(date.getTime());         
        
         try{
                       String sql="insert into Item_inventory values(?,?,?,?,?)";
           pst=conn.prepareStatement(sql);
           pst.setString(1,txtcode.getText());
           pst.setString(2,txtname.getText());
            pst.setDate(3,sqldate);
           pst.setString(4,txtquentity.getText());
                            
           pst.setString(5,txtprice.getText());
           
          // rs=pst.executeQuery();
           int i=pst.executeUpdate();
         
           
           if(i>0){
               
               updated();
                JOptionPane.showMessageDialog(null,"Successfully Added");
                upt();
                updatetab();
                
               rs.close();
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,"Item code already exist !");
            
        }
    }
         
    }//GEN-LAST:event_AddItem_jButton1ActionPerformed

    public void updated(){
        
        java.util.Date date;
               java.sql.Date sqldate;
               
               date= txtdate.getDate();
               sqldate=new java.sql.Date(date.getTime());
        
        try{
                       String sql="insert into updt values(?,?,?)";
           pst=conn.prepareStatement(sql);
           pst.setString(1,txtcode.getText());
           pst.setString(2,txtquentity.getText());
            pst.setDate(3,sqldate);
           
                            
          
           
          // rs=pst.executeQuery();
           int i=pst.executeUpdate();
        }
        catch(Exception i){
            
        }
    
}
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        dispose();
        main s1= new main();
               s1.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
        if((txtprice.getText().isEmpty())&&ItemCodevalidation(txtcode.getText())&&Quentityvalidation(txtquentity.getText())){
           
            java.util.Date date;
               java.sql.Date sqldate;
               
               date= txtdate.getDate();
               sqldate=new java.sql.Date(date.getTime());
            try{
                     
           String v1=txtquentity.getText();
        //  String v2=txtdate.getText();
          String v3=txtcode.getText();
          
           
          double vx=calreject(v3);
          double vx1=Double.parseDouble(v1);
          double x=vx+vx1;
                    String sql="update Item_inventory set Quantity="+x+" where Item_code="+v3;
           pst=conn.prepareStatement(sql);
           int i=pst.executeUpdate();
           
               rs.close();
               
         
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Successfully updated");
                updatetab();
                
                //insert in to update table
                String sql1="insert into updt values(?,?,?)";
           pst=conn.prepareStatement(sql1);
           pst.setString(1,txtcode.getText());
           pst.setString(2,txtquentity.getText());
                     
           pst.setDate(3,sqldate);
           
           pst.executeUpdate();
                upt();
               rs.close();
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
        }
        else if((txtquentity.getText().isEmpty())&&ItemCodevalidation(txtcode.getText())&&Pricevalidation(txtprice.getText())){
               try{
                     
          // String v1=txtquentity.getText();
          String v2=txtprice.getText();
          String v3=txtcode.getText();
          
                    String sql="update Item_inventory set unitPrice="+v2+" where Item_code="+v3;
           pst=conn.prepareStatement(sql);
           int i=pst.executeUpdate();
        // rs.close();
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Successfully updated");
                updatetab();
                
            
                
               
                
               rs.close();
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
            
        }
        
        else if(ItemCodevalidation(txtcode.getText())&&Quentityvalidation(txtquentity.getText())&&Pricevalidation(txtprice.getText())){
            java.util.Date date;
               java.sql.Date sqldate;
               
               date= txtdate.getDate();
               sqldate=new java.sql.Date(date.getTime());  
            try{
                     
           String v1=txtquentity.getText();
          String v2=txtprice.getText();
          String v3=txtcode.getText();
          
          double vx=calreject(v3);
          double vx1=Double.parseDouble(v1);
          double x=vx+vx1;
          
                    String sql="update Item_inventory set unitPrice="+v2+" ,Quantity="+x+" where Item_code="+v3;
           pst=conn.prepareStatement(sql);
           int i=pst.executeUpdate();
         
           rs.close();
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Successfully updated");
                updatetab();
                
                    String sql1="insert into updt values(?,?,?)";
           pst=conn.prepareStatement(sql1);
           pst.setString(1,txtcode.getText());
           pst.setString(2,txtquentity.getText());
                     
           pst.setDate(3,sqldate);
           pst.executeUpdate();
                upt();
               rs.close();
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
            
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    public double calreject(String v){
    try{
    String sql="select * from Item_inventory where Item_code="+v;
   pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
           
           if(rs.next()){
               
               
                 String a11=rs.getString("Quantity");
                 double q=Double.parseDouble(a11);
                 rs.close();
               return q;
               
           }
    }
    catch(Exception e){
    }
    return 0;
}
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
          try{
                     
          // String v1=txtquentity.getText();
        //  String v2=txtprice.getText();
        
          String v3=txtcode.getText();
          
                String sql1="select * from Item_inventory where Item_code=?";
           pst=conn.prepareStatement(sql1);
           pst.setString(1,v3);
           rs=pst.executeQuery();
           if(rs.next()){
                String a1=rs.getString("Quantity");
                
                
                double p=Double.parseDouble(a1);
                
                
               if(p>0){
               JOptionPane.showMessageDialog(null,"Quentity NOT cleared !");
               
           }
               else{
          
                    String sql="delete from  item_inventory where item_code='"+v3+"' ";
           pst=conn.prepareStatement(sql);
           //to delete from update table
        //     String sql1="delete from updt where code='"+v3+"'";
          // pst=conn.prepareStatement(sql1);
           int i=pst.executeUpdate();
         
           
           if(i>0){
               
                JOptionPane.showMessageDialog(null,"Successfully Deleted");
                updatetab();
                
               rs.close();
               
           }
           else{
                JOptionPane.showMessageDialog(null,"wrong input");
           }
           }
        }
         }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        txtcode.setText(null);
        txtdate.setDate(null);
        txtname.setText(null);
        txtprice.setText(null);
        txtquentity.setText(null);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        try{
        String report ="C:\\CompanyMSys\\Settings\\Inventory\\inventory1.jasper";
       // JasperReport rep= JasperCompileManager.compileReport(report);
        JasperPrint pri=JasperFillManager.fillReport(report,null,conn);
       
      JRViewer jv = new JRViewer(pri);
          
               JFrame jf = new JFrame();
            jf.getContentPane().add(jv);
            jf.validate();
            jf.setVisible(true);
            jf.setSize(new Dimension(1200,1000));
            jf.setLocation(50,100);

        }
        catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(additems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(additems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(additems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(additems.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new additems().setVisible(true);
                
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddItem_jButton1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField textsrch;
    private javax.swing.JTextField txtcode;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtprice;
    private javax.swing.JTextField txtquentity;
    // End of variables declaration//GEN-END:variables
}
