/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Inventory;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import static Inventory.partvalid.ItemCodevalidation;
import static Inventory.partvalid.Namevalidation;
import static Inventory.partvalid.Pricevalidation;
import static Inventory.partvalid.Quentityvalidation;
import com.itextpdf.text.Document;
import java.awt.font.*;

import com.itextpdf.text.pdf.PdfWriter;

import java.io.OutputStream;

import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Font;

import com.itextpdf.text.Phrase;

import com.itextpdf.text.pdf.codec.Base64;

import java.io.File;

import java.io.FileOutputStream;

import java.util.Date;
import com.itextpdf.text.Image;
//import java.awt.Font;

import com.itextpdf.text.pdf.BaseFont;
/**
 *
 * @author hp
 */
public class calculation extends javax.swing.JFrame {
       
    Connection conn=null;
ResultSet rs=null;
PreparedStatement pst=null;
    /**
     * Creates new form calculation
     */
    public calculation() {
    initComponents();
        try {
            conn = connection.condb();
        } catch (SQLException ex) {
            Logger.getLogger(calculation.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        code = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        fdate = new com.toedter.calendar.JDateChooser();
        tdate = new com.toedter.calendar.JDateChooser();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(32, 47, 90));

        jPanel2.setBackground(new java.awt.Color(106, 116, 145));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Item Code    :");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        code.setBackground(new java.awt.Color(106, 116, 145));
        code.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        code.setForeground(new java.awt.Color(255, 255, 255));
        code.setBorder(null);
        code.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codeActionPerformed(evt);
            }
        });
        jPanel2.add(code, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 20, 133, 29));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 133, 12));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("From Date    :");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("To Date         :");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, -1, -1));

        jButton1.setBackground(new java.awt.Color(204, 180, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Calculate Difference");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 260, 40));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Total Amount recived        :");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total Amount rejected      :");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Difference                          :");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 240, 160, 20));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 274, 150, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 314, 150, 30));

        fdate.setDateFormatString(" yyyy-MM-dd");
        jPanel2.add(fdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 130, -1));

        tdate.setDateFormatString(" yyyy-MM-dd");
        jPanel2.add(tdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 130, -1));

        jPanel3.setBackground(new java.awt.Color(106, 116, 145));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Close Compare Report");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 25, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 511, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 480));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void codeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
           if(ItemCodevalidation(code.getText())){
                    
         java.util.Date date;
               java.sql.Date sqldate;
               
               date= fdate.getDate();
               sqldate=new java.sql.Date(date.getTime());
               
               java.util.Date date1;
               java.sql.Date sqldate1;
               
               date1= tdate.getDate();
               sqldate1=new java.sql.Date(date1.getTime());
         try{
             
             
             String v=code.getText();
             String v1=sqldate.toString();
             String v2=sqldate1.toString();
            // int x =Integer.parseInt(v);
          // i,updt q where q.Code='"+v+"'and i.Item_code='"+v+"'and q.date between'"+v1+"'and'"+v2+"'
         
              double q=calreject(v, v1, v2);
               jLabel8.setText(q+"/=");
               double i=calqinventoty(v, v1, v2);
                 jLabel7.setText(i+"/=");
                 
                 String name =name(v);
                 String supnam=supname(v);
               
              // double p=Double.parseDouble(a10);
              //  double q=a11;
                if(q>0&&i>0){
                double r=i-q;
                jLabel9.setText(r+"/=");
                FileOutputStream out= new FileOutputStream(new File("C:\\CompanyMSys\\Payment\\"+name+"_of_"+v1+"_to_"+v2+".pdf"));

               Document doc = new Document();

               PdfWriter wr =PdfWriter.getInstance(doc,out);
               doc.open();
                    BaseFont bf =BaseFont.createFont(BaseFont.TIMES_BOLD,BaseFont.CP1252,BaseFont.EMBEDDED);
                    Font f=new Font(bf,26);
                    
                    BaseFont bf1 =BaseFont.createFont(BaseFont.TIMES_ROMAN,BaseFont.CP1252,BaseFont.EMBEDDED);
                    Font f1=new Font(bf1,18);
                    
               doc.add(Image.getInstance("C:\\CompanyMSys\\Settings\\g.png"));
               doc.add(new Paragraph(" "));
               doc.add(new Paragraph(" "));
               doc.add(new Paragraph("PAYMENT REPORT",f));
               doc.add(new Paragraph(" "));
               doc.add(new Paragraph("** You're item name is                              :  "+name,f1));
               doc.add(new Paragraph("** Supplier name is                                   :  "+supnam,f1));
               doc.add(new Paragraph("** Date From                                             :  "+v1,f1));
               doc.add(new Paragraph("** Date To                                                 :  "+v2,f1));
               doc.add(new Paragraph("** "+name+" item recived amount  :  "+i,f1));
               doc.add(new Paragraph("** "+name+" item rejected amount :  "+q,f1));
               doc.add(new Paragraph("** "+name+" item  total payment is :  "+r,f1));

               doc.add(new Paragraph(" "));
               doc.add(new Paragraph(" "));

               doc.add(new Paragraph("THANK YOU !",f));

               doc.close();
                
                }
                
               else
                    jLabel9.setText("No Difference");
                    
         
           
          // else{
               // JOptionPane.showMessageDialog(null,"wrong input");
          // }
            
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
            
        }
           }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
         dispose();
        damage s2= new damage();
               s2.setVisible(true);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
         dispose();
        damage s2= new damage();
               s2.setVisible(true);
    }//GEN-LAST:event_jPanel3MouseClicked
public double calreject(String v,String v1,String v2){
    try{
    String sql="select sum(q.Quantity)*i.unitPrice from Item_inventory i,damage_item q where q.ItemCode='"+v+"'and i.Item_code='"+v+"'and q.ReturnDate between'"+v1+"'and'"+v2+"' ";
   pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
           
           if(rs.next()){
               
               
                 String a11=rs.getString(1);
                 double q=Double.parseDouble(a11);
                 rs.close();
               return q;
               
           }
    }
    catch(Exception e){
    }
    return 0;
}

public double calqinventoty(String v,String v1,String v2){
    try{
      String sqli="select sum(qunt)*i.unitPrice from item_inventory i, updt r where r.code='"+v+"'and i.Item_code='"+v+"'and r.date between'"+v1+"'and'"+v2+"' ";
           pst=conn.prepareStatement(sqli);
      
           
           rs=pst.executeQuery();
           
           if(rs.next()){
               String a10=rs.getString(1);
               double i=Double.parseDouble(a10);
             
               rs.close();
               return i;
           }
    }
             catch(Exception e){
    }
    return 0;
    
}

public String  name(String v){
  try{
    String sql="select Item_name  from Item_inventory  where Item_code="+v+"";
   pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
           
           if(rs.next()){
               
               
                 String a11=rs.getString(1);
                
                 rs.close();
               return a11;
               
           }
    }
    catch(Exception e){
    }
    return null;
}

public String  supname(String v){
  try{
    String sql="select SupplierName   from damage_item  where ItemCode="+v+"";
   pst=conn.prepareStatement(sql);
    rs=pst.executeQuery();
           
           if(rs.next()){
               
               
                 String a11=rs.getString(1);
                
                 rs.close();
               return a11;
               
           }
    }
    catch(Exception e){
    }
    return null;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(calculation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new calculation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField code;
    private com.toedter.calendar.JDateChooser fdate;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.calendar.JDateChooser tdate;
    // End of variables declaration//GEN-END:variables
}
